name: freshgarden
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  qr_code_scanner: ^0.7.0
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/home_menu.svg
    - assets/drawer_checkout.svg
    - assets/drawer_cart.svg
    - assets/drawer_customer.svg
    - assets/drawer_product.svg
    - assets/drawer_setting.svg
    - assets/drawer_user.svg
    - assets/tab_add.svg
    - assets/tab_collection.svg
    - assets/tab_scan.svg
    - assets/tab_flash.svg
    - assets/newproduct_image.svg
    - assets/payment_tag.svg
    - assets/setting_general.svg
    - assets/setting_saletax.svg
    - images/product.png
    - images/customer_avatar.png
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: RobotoBold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: RobotoMedium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
    - family: HelveticaBold
      fonts:
        - asset: fonts/Helvetica-Bold.ttf
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
